apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  annotation:
    - kubernetes.io/change-cause="image updated to 1.14"

spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14
        ports:
        - containerPort: 80