
- name: "My step2 play []"
  hosts: master-1  ## all, 
  tasks:
  - name: helm3 설치
    shell: |
      curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash    
    tags: 
      - helm3 
      - step2
  - name: bitnami  repository 추가 
    kubernetes.core.helm_repository:
      name: bitnami
      repo_url: https://charts.bitnami.com/bitnami
    tags: 
      - bitnami-repo
      - step2
      
  - name: redis 설치
    kubernetes.core.helm:
      name: redis
      chart_ref: bitnami/redis
      chart_version: "{{REDIS_CHART_VERSION}}"
      release_namespace: "{{REDIS_NAMESPACE}}"
      create_namespace: true
      values:
        master:
          persistence:
            enabled: false 
        replica:
          persistence:
            enabled: false
      wait: true
    register: output
    tags: 
      - redis
      - step2

  - debug:
    var: output
    tags: 
      - redis
      - step2