
- name: "k8s CD 배포 "
  hosts: all  ## all, 

  tasks:
  - name: "kubectl, kubeconfig 설정"
    shell: |
      mkdir -p ~/.kube/
      cp /etc/rancher/rke2/rke2.yaml ~/.kube/config
      sudo cp /var/lib/rancher/rke2/bin/kubectl /usr/local/bin/
    tags: 
      - kube-pre
      - argocd

  - name: "[Global-pre] down 디렉토리 생성"
    shell: |
      mkdir -p ./install
    tags: 
      - upload
      - argocd

  - name: files upload   
    copy:
      src: "argocd-ing.yaml"
      dest:  "install/"  
    tags: 
      - upload
      - argocd

  - name: argocd 설치
    shell: |
      kubectl create ns argocd
      kubectl -n argocd apply  -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
      sleep 20
      kubectl wait pod --timeout=-1s --for=condition=Ready -l '!job-name' -n argocd  > /dev/null
    
    register: output
    tags: 
      - argocd
  - debug:
      var: output
    tags: 
      - argocd

  - name: argocd 설치
    shell: |
      kubectl apply -f install/argocd-ing.yaml
    tags: 
      - argocd-ing
      - argocd

  - name: argocd-cli 설치 
    shell: |
      sudo curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
      sudo chmod +x /usr/local/bin/argocd
    tags: 
      - argocd-cli 